name: BranchPush workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - develop
      - '**'
    pull_request:
      - master
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
      - ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # fetch-depth:0 is needed to get tags too
      # normal builds do not need history.
      # https://github.com/actions/checkout/tags
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      # https://github.com/actions/setup-java/tags
      - name: Set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'temurin'
          java-version: 17

      # https://github.com/leafo/gh-actions-lua/tags
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3.5"

      # Runs a single command using the runners shell
      - name: Build with ant
        run: ant package

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.6.1
        if: always()
        with:
          files: target/reports/*.xml
