name: Tag - Create Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on:
      - ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout code
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3.5"

      # Runs a single command using the runners shell
      - name: Build with ant
        run: ant package; ls ./target/*.love*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: target/working/changelog.txt
          draft: false
          prerelease: false

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          asset_paths: '["./target/*.love*"]'
